Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TournamentsWebApp.Data;
using TournamentsWebApp.Models;

namespace TournamentsWebApp.Controllers
{
    public class MatchesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public MatchesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Matches/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = await _context.Matches.FindAsync(id);
            if (match == null)
            {
                return NotFound();
            }
            var list = new List<string> { match.LicenceNumberFirst, match.LicenceNumberSecond };
            ViewData["Players"] = new SelectList(list);

            return View(match);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,WinnerID,TournamentID,OpponentFirstID", "OpponentSecondID", "LicenceNumberFirst", "LicenceNumberSecond")] Match match)
        {
            if (id != match.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var userID = _userManager.GetUserId(User);

                    lock(Lock.resultLock){
                        var matchMain =  _context.Matches.Find(id);
                        _context.Entry(matchMain).State = EntityState.Detached;

                        if (matchMain.OpponentFirstID == null || matchMain.OpponentSecondID == null)
                        {
                            return RedirectToAction("Index", "Tournaments");
                        }


                        if (matchMain.lastEditor == userID)
                        {
                            return RedirectToAction("Index", "Tournaments");
                        }

                        if(matchMain.isFinished == true)
                        {
                            return NotFound();
                        }

                        if (userID != matchMain.OpponentFirstID && userID != matchMain.OpponentSecondID)
                        {
                            return NotFound();
                        }
                        if (match.OpponentFirstID != matchMain.OpponentFirstID || match.OpponentSecondID != matchMain.OpponentSecondID)
                        {
                            return NotFound();
                        }
                        if (match.WinnerID != matchMain.LicenceNumberFirst && match.WinnerID != matchMain.LicenceNumberSecond)
                        {
                            return NotFound();
                        }

                        if (match.TournamentID != matchMain.TournamentID)
                        {
                            return NotFound();
                        }

                        match.LicenceNumberFirst = matchMain.LicenceNumberFirst;
                        match.LicenceNumberSecond = matchMain.LicenceNumberSecond;
                        match.nextMatchNumber = matchMain.nextMatchNumber;
                        match.MatchNumber = matchMain.MatchNumber;

                        if (matchMain.TemporaryResult == null || matchMain.TemporaryResult == "-1")
                        {
                            match.lastEditor = userID;
                            match.TemporaryResult = match.WinnerID;
                            match.WinnerID = null;

                        }
                        else
                        {
                            if (matchMain.TemporaryResult == match.WinnerID)
                            {

                                match.isFinished = true;

                            }
                            else
                            {
                                match.TemporaryResult = "-1";
                                match.WinnerID = null;
                            }
                        }
                    }

                    _context.Update(match);
                    await _context.SaveChangesAsync();

                    if(match.isFinished && match.nextMatchNumber != null)
                    {
                        var nextMatch = await _context.Matches.Include(m => m.OpponentFirst).Include(m => m.OpponentSecond).Include(m => m.tournament)
                            .Where(m => m.TournamentID == match.TournamentID).Where(m => m.MatchNumber == match.nextMatchNumber).FirstOrDefaultAsync();

                        var licence = "";
                        if (match.WinnerID == match.LicenceNumberFirst)
                        {
                            match.WinnerID = match.OpponentFirstID;
                            licence = match.LicenceNumberFirst;
                        }
                        else
                        {
                            match.WinnerID = match.OpponentSecondID;
                            licence = match.LicenceNumberSecond;
                        }

                        if(nextMatch.OpponentFirstID == null)
                        {
                            nextMatch.OpponentFirstID = match.WinnerID;
                            nextMatch.LicenceNumberFirst = licence;
                        }
                        else
                        {
                            nextMatch.OpponentSecondID = match.WinnerID;
                            nextMatch.LicenceNumberSecond = licence;
                        }
                        _context.Update(nextMatch);
                        await _context.SaveChangesAsync();
                    }
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MatchExists(match.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Tournaments");
            }

            var correct = await _context.Matches.FindAsync(id);
            _context.Entry(correct).State = EntityState.Detached;
            if (match == null)
            {
                return NotFound();
            }
            var list = new List<string> { correct.LicenceNumberFirst, correct.LicenceNumberSecond };
            ViewData["Players"] = new SelectList(list);

            return View(match);
        }


        private bool MatchExists(int id)
        {
            return _context.Matches.Any(e => e.ID == id);
        }
    }
}

Controllers/TournamentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TournamentsWebApp.Data;
using TournamentsWebApp.Models;
using TournamentsWebApp.Services;


namespace TournamentsWebApp.Controllers
{
    public class TournamentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAuthorizationService _authorizationService;
        
        public TournamentsController(IAuthorizationService authorizationService, ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _authorizationService = authorizationService;
            _context = context;
            _userManager = userManager;
        }

        // GET: Tournaments
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;

            ViewData["NameSortParm"] = sortOrder == "name" ? "name_desc" : "name";

            ViewData["DateSortParm"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;


            var tournaments = from row in _context.Tournament select row;

            if (!String.IsNullOrEmpty(searchString))
            {
                tournaments = tournaments.Where(s => s.Name.Contains(searchString)
                                       || s.StartDate.ToString().Contains(searchString));
            }
            

            switch (sortOrder)
            {
                case "name_desc":
                    tournaments = tournaments.OrderByDescending(s => s.Name).ThenBy(s => s.StartDate);
                    break;
                case "name":
                    tournaments = tournaments.OrderBy(s => s.Name).ThenBy(s => s.StartDate);
                    break;
                case "date_desc":
                    tournaments = tournaments.OrderByDescending(s => s.StartDate).ThenBy(s => s.Name);
                    break;
                default:
                    tournaments = tournaments.OrderBy(s => s.StartDate).ThenBy(s => s.Name); ;
                    break;
            }

            int pageSize = 10;
            return View(await PaginatedList<Tournament>.CreateAsync(tournaments.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Tournaments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tournament = await _context.Tournament.Include(m => m.Owner).FirstOrDefaultAsync(m => m.ID == id);

            if (tournament == null)
            {
                return NotFound();
            }

            if(tournament.StartDate < DateTime.Now && tournament.isBracket == false)
            {
                Bracket.generateBracket(_context, tournament);
            }

            if (tournament.isBracket)
            {
                return RedirectToAction("Started", new { id }); //view z drabinka
            }
            else
            {
                var logos = await _context.Logos.Include(m => m.tournament).Where(m => m.TournamentId == id).ToListAsync();
                var model = new DetailsModel
                {
                    tournament = tournament,
                    allLogos = logos
                };
                return View(model);
            }
        }


        public async Task<IActionResult> Started(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tournament = await _context.Tournament.Include(m => m.Owner).FirstOrDefaultAsync(m => m.ID == id);
            var allMatches = await _context.Matches.Include(m => m.OpponentFirst).Include(m => m.OpponentSecond).Include(m => m.tournament).Where(m => m.TournamentID == id).ToListAsync();
            var logos = await _context.Logos.Include(m => m.tournament).Where(m => m.TournamentId == id).ToListAsync();
            var userID = _userManager.GetUserId(User);
            List<Match> userMatches = null;

            if (userID != null)
            {
                userMatches = allMatches.Where(m =>( m.OpponentFirstID == userID || m.OpponentSecondID == userID )&& m.isFinished != true ).ToList();
            }


            var bracket = new List<List<List<BracketModel>>>();
            var round = new List<List<BracketModel>>();

            for (var i = 0; i < allMatches.Count; i++ )
            {
                var b1 = new BracketModel
                {
                    name = allMatches[i].LicenceNumberFirst ?? "TBD",
                    id = allMatches[i].LicenceNumberFirst  
                };

                var b2 = new BracketModel
                {
                    name = allMatches[i].LicenceNumberSecond ?? "TBD",
                    id = allMatches[i].LicenceNumberSecond 
                };
                var match = new List<BracketModel> { b1, b2 };
                round.Add(match);
                if(allMatches[i].MatchNumber != 1 && ((allMatches[i].MatchNumber - 1) & allMatches[i].MatchNumber) == 0)
                {
                    bracket.Add(round);
                    round = new List<List<BracketModel>>();
                }

            }
            bracket.Add(round);

            allMatches.Reverse();
            bracket.Reverse();
            var x = new BracketModel
            {
                name = allMatches.Last().WinnerID ?? "TBD",
                id = allMatches.Last().WinnerID
            };
            var dM = new List<BracketModel>() { x };
            bracket.Add(new List<List<BracketModel>>() { dM });

            

            var model = new ViewModel
            {
                bracket = bracket,
                allMatches = allMatches,
                userMatches = userMatches,
                tournament = tournament,
                allLogos = logos
            };


            return View(model);
        }


        [Authorize]
        // GET: Tournaments/Create
        public IActionResult Create()
        {
            return View();
        }


        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,StartDate,Deadline,Discipline,localization,maxPart")] Tournament tournament)
        {
            if (ModelState.IsValid)
            {
                tournament.Owner = await _userManager.GetUserAsync(User);
                _context.Add(tournament);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
           
            return View(tournament);
        }

        // GET: Tournaments1/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tournament = await _context.Tournament.Include(m => m.Owner).FirstOrDefaultAsync(m => m.ID == id);
            if (tournament == null)
            {
                return NotFound();
            }

            var userID = _userManager.GetUserId(User);
            var ownerID = tournament.Owner.Id;
            if (ownerID == userID)
                return View(tournament);
            else
                return RedirectToAction(nameof(Index));

        }


        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,StartDate,Deadline,Discipline,currentPart,localization,maxPart")] Tournament tournament)
        {
            if (id != tournament.ID)
            {
                return NotFound();
            }
            

            var current = await _context.Tournament.Include(m => m.Owner).FirstOrDefaultAsync(m => m.ID == id);
            _context.Entry(current).State = EntityState.Detached;

            if (current.isBracket == true)
            {
                //todo info
                return NotFound();
            }

            var userID = _userManager.GetUserId(User);
            var ownerID = current.Owner.Id;
            if (ownerID != userID)
                return RedirectToAction(nameof(Index));



            lock (Lock.partLock)
            {
                tournament.currentPart = current.currentPart;
                if (ModelState.IsValid && tournament.currentPart <= tournament.maxPart)
                {
                    try
                    {

                        _context.Update(tournament);
                        _context.SaveChanges();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!TournamentExists(tournament.ID))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(tournament);
        }

        // GET: Tournaments1/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tournament = await _context.Tournament.Include(m => m.Owner).FirstOrDefaultAsync(m => m.ID == id);

Views/Tournaments/Add_sponsors.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Tournaments/Create.cshtml
@model TournamentsWebApp.Models.Tournament

@{
    ViewData["Title"] = "Create";
}

<h1>Create Own Tournament</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discipline" class="control-label"></label>
                <input asp-for="Discipline" class="form-control" />
                <span asp-validation-for="Discipline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="localization" class="control-label"></label>
                <input asp-for="localization" class="form-control" />
                <span asp-validation-for="localization" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="maxPart" class="control-label"></label>
                <input asp-for="maxPart" class="form-control" />
                <span asp-validation-for="maxPart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" onclick="return confirm('Are you sure?');"
 />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tournaments/Delete.cshtml
@model TournamentsWebApp.Models.Tournament

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tournament</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Discipline)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Discipline)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.localization)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.localization)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.currentPart)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.currentPart)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.maxPart)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.maxPart)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure?');"
/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Tournaments/Edit.cshtml
@model TournamentsWebApp.Models.Tournament

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Tournament</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="currentPart" />
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discipline" class="control-label"></label>
                <input asp-for="Discipline" class="form-control" />
                <span asp-validation-for="Discipline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="localization" class="control-label"></label>
                <input asp-for="localization" class="form-control" />
                <span asp-validation-for="localization" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="maxPart" class="control-label"></label>
                <input asp-for="maxPart" class="form-control" />
                <span asp-validation-for="maxPart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tournaments/Started.cshtml
@model TournamentsWebApp.Models.ViewModel
@using Microsoft.AspNetCore.Authorization
@using TournamentsWebApp.Models;
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> userManager
@inject IAuthorizationService AuthorizationService
@{
    ViewData["Title"] = "Details";
}

<h1> "@Model.tournament.Name" Tournament Details  </h1>

<h3> Tournament has started! </h3>

<fieldset>
    <legend style="font-family: 'Segoe UI'; color: rgb(73,171,210); font-size: large;">Tournament location:</legend>
    <iframe width="100%"
            height="400px"
            style="border:0"
            loading="lazy"
            allowfullscreen
            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBkScl8QvQwXr1qdINMPHMC1tEuMx3Va34&q=@Model.tournament.localization">
    </iframe>
    <!--
    <div id="googleMap" style="height:400px;width:100%;"></div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>

        function myMap() {
            var myCenter = new google.maps.LatLng(52.403440, 16.950744);
            var geocoder = new google.maps.Geocoder();
            geocoder.geocode({ 'address': "@Model.tournament.localization" }, function (results, status) {
                if (status == 'OK') {
                    myCenter = results[0].geometry.locationl
                    alert('Geocode was OK' );
                } else {
                    alert('Geocode was not successful for the following reason: ' + status);
                }
            });

            var mapProp = { center: myCenter, zoom: 12, scrollwheel: false, draggable: true, mapTypeId: google.maps.MapTypeId.ROADMAP };
            var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
            var marker = new google.maps.Marker({ position: myCenter });
            marker.setMap(map);
        }
    </script>
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBkScl8QvQwXr1qdINMPHMC1tEuMx3Va34&callback=myMap"></script> -->
</fieldset>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.tournament.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.tournament.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.tournament.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.tournament.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.tournament.Deadline)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.tournament.Deadline)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.tournament.Discipline)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.tournament.Discipline)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.tournament.localization)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.tournament.localization)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.tournament.currentPart)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.tournament.currentPart)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.tournament.maxPart)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.tournament.maxPart)
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && Model.userMatches.Count > 0)
    {
        <h3> Your next matches:</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        <p> First opponent</p>
                    </th>
                    <th>
                        <p> Second Opponent</p>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.userMatches)
                {
                    <tr>
                        <td>
                            @if (item.OpponentFirst is null)
                            {
                                <p> TBD </p>}
                            else
                            {
                                var toShow = item.OpponentFirst.FirstName + " Licence:" + item.LicenceNumberFirst;
                                @Html.DisplayFor(modelItem => toShow)
                            }
                        </td>
                        <td>
                            @if (item.OpponentSecond is null)
                            {
                                <p> TBD </p>}
                            else
                            {
                                var toShow = item.OpponentSecond.FirstName + " Licence:" + item.LicenceNumberSecond;
                                @Html.DisplayFor(modelItem => toShow)
                            }

                        </td>
                        <td>
                            @if (item.OpponentSecondID != null && item.OpponentFirstID != null)
                            {
                                <a asp-controller="Matches" asp-action="Edit" asp-route-id="@item.ID">Set result</a>
                            }


                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }


    <!---            DRABINKA                  -->

    <div class="my_gracket"></div>
    <script type="text/javascript">
    $(document).ready(function ($) {
            var data = @Html.Raw(Json.Serialize(Model.bracket))
            $(".my_gracket").gracket({
                src: data
            });

        })

    </script>



    <!---            DRABINKA                  -->


    <table class="table">
        <thead>
            <tr>
                <th>
                    <p> First opponent</p>
                </th>
                <th>
                    <p> Second Opponent</p>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.allMatches)
            {
                <tr>
                    <td>
                        @if (item.OpponentFirst is null)
                        {
                            <p> TBD </p>}
                        else
                        {
                            var toShow = item.OpponentFirst.FirstName + " Licence:" + item.LicenceNumberFirst;
                            @Html.DisplayFor(modelItem => toShow)
                        }
                    </td>
                    <td>
                        @if (item.OpponentSecond is null)
                        {
                            <p> TBD </p>}
                        else
                        {
                            var toShow = item.OpponentSecond.FirstName + " Licence:" + item.LicenceNumberSecond;
                            @Html.DisplayFor(modelItem => toShow)
                        }

                    </td>
                </tr>
            }
        </tbody>
    </table>
    @if (Model.allMatches.Last().WinnerID != null)
    {
        <h2> Winner: @Model.allMatches.Last().WinnerID</h2>

    }


    <a asp-action="Index">Back to List</a>
    <div> </div>
    <h4>Sponsors: </h4>
    <ul>
        @foreach (var i in Model.allLogos)
        {
            <li>
                <img src=@i.link style="padding:20px; max-width: auto; height: 150px">
            </li>
        }
    </ul>

</div>